#!/usr/bin/env python
import os
import sys
import subprocess
import re

class _Options(object):
  help = False

class CloneFailure(Exception):

  """Indicate the remote clone of repo itself failed.
  """
 
def _ParseArguments(args):
  cmd = None
  opt = _Options()
  arg = []

  for i in range(len(args)):
    a = args[i]
    if a == '-h' or a == '--help':
      opt.help = True

    elif not a.startswith('-'):
      cmd = a
      arg = args[i + 1:]
      break
  return cmd, opt, arg

def _CloneSubRepos(args):
  f = open(args[0],'r')
  lines = f.read().splitlines()
  for line in lines:
    if os.path.isdir(re.split(r',',line)[0]):
      print "crepo: folder exist"
      continue
    cmd = ['git', 'clone']
    repo = re.split(r',',line)[1]
    cmd.extend([repo])
    subprocess.Popen(cmd)
    del cmd
  f.close()
  cmd = ['cp']
  cmd.extend([args[0]])
  cmd.extend(['default.tag'])
  subprocess.Popen(cmd)
  print "crepo: init done"
  return

def _SyncSubRepos():
  if 0 == os.path.isfile('default.tag'):
    print "fatal: no default file. Please crepo init"
    return
  f = open('default.tag','r')
  lines = f.read().splitlines()
  cwd = os.getcwd()
  for line in lines:
    if os.path.isdir(re.split(r',',line)[0]):
      cmd = ['git', 'checkout','-b','local']
      version = re.split(r',',line)[2]
      cmd.extend([version])
      os.chdir(re.split(r',',line)[0])
      try:
        subprocess.Popen(cmd)
      except OSError as e:
        print 'git checkout fatal!'
      os.chdir(cwd)
      del cmd
    else:
      print ('fatal! git repo does not exsit: %s' % re.split(r',',line)[0])
  f.close()
  print "crepo: sync done"
  return


def main(orig_args):
  cmd, opt, args = _ParseArguments(orig_args)

#   if opt.help:
#     _Usage()
#   if cmd == 'help':
#     _Help(args)
  cwd = os.getcwd()
  if cmd == 'init':
    try:
     _CloneSubRepos(args);
    except CloneFailure:
      print("fatal: cloning the git-crepo repository failed, will remove %s ")
      sys.exit(1)
  elif cmd == 'sync':
    try:
     _SyncSubRepos();
    except CloneFailure:
      print("fatal: sync failed")
      sys.exit(1)
  else:
    try:
      print "TBD"
#     os.execv(sys.executable, me)
    except OSError as e:
      print("fatal: %s" % e)#, file=sys.stderr)
      sys.exit(148)


if __name__ == '__main__':
  main(sys.argv[1:])
